name: matrix_value_from_file_action
description: |
  Make matrix values for next jobs.

  matrix_value_from_file_action action is designed to make matrix value(eg. `"["test1", "test2"]"`)
  Using matrix makes us to handle loop procedures.
  This action will run following steps:

  0. (caller's step) Write multiline values to a plain text file.
  1. Convert the plain text file to a json file.
  2. Convert the json file to a compacted array using jq and stored in the output.

inputs:
  file_path:
    description: file path
    required: true
outputs:
  result:
    description: matrix value result
    value: ${{ steps.matrix_value.outputs.result }}
runs:
  using: composite
  steps:
    - name: make json file
      uses: actions/github-script@v6
      env:
        FILE_PATH: ${{ inputs.file_path }}
      with:
        script: |
          const fs = require('fs')
          const filePath = process.env.FILE_PATH
          const fileData = fs.readFileSync(filePath, 'utf-8')
          const fileArray = fileData.split("\n").filter(Boolean)
          fs.writeFileSync(`${filePath}.json`, JSON.stringify(fileArray))
    - name: set matrix value
      id: matrix_value
      shell: bash
      run: |
        echo "result=$(cat ${{ inputs.file_path }}.json | jq -c)" >> "${GITHUB_OUTPUT}"
